### PR TITLE
Compat for Julia 0.7

### PR DESCRIPTION
**Pull request by iamed2**

### CODE REVIEW

**Review by ararslan — APPROVED** [review]

**Comment by rofinn** [comment]
Any idea what's causing this issue on 0.7 linux?

```
ERROR: LoadError: LoadError: could not load library "libc"
/usr/lib/x86_64-linux-gnu/libc.so: invalid ELF header
```

**Comment by ararslan** [comment]
I can check on my Linux machine tomorrow to see if I can reproduce it. I know the internal shared object version mapping changed (or rather was gutted) in 0.7, so it could be something to do with that.

**Comment by ararslan** [comment]
Yep, I can reproduce. Looks like the issue is indeed the version mapping. I needed to provide the version for libc for it to work, plus since libc is linked into Julia, we don't need to explicitly tell `ccall` to use libc. This worked for me:
```diff
--- a/src/Syslogs.jl
+++ b/src/Syslogs.jl
@@ -88,12 +88,12 @@ const FACILITIES = Dict(
 )
 
 openlog(ident::String, logopt::Integer, facility::Integer) =
-    ccall((:openlog, "libc"), Cvoid, (Ptr{UInt8}, UInt, UInt), ident, logopt, facility)
+    ccall(:openlog, Cvoid, (Ptr{UInt8}, UInt, UInt), ident, logopt, facility)
 
 syslog(priority::Integer, msg::String) =
-    ccall((:syslog, "libc"), Cvoid, (UInt, Ptr{UInt8}), priority, msg)
+    ccall(:syslog, Cvoid, (UInt, Ptr{UInt8}), priority, msg)
 
-closelog() = ccall((:closelog, "libc"), Cvoid, ())
+closelog() = ccall(:closelog, Cvoid, ())
 
 makepri(facility::Integer, priority::Integer) = (UInt(facility) << 3) | UInt(priority)
```
```diff
--- a/test/helpers.jl
+++ b/test/helpers.jl
@@ -1,4 +1,4 @@
-const LIBC = Libdl.dlopen("libc")
+const LIBC = Libdl.dlopen("libc.so.6")
 
 exists(lib::Ptr, sym::Symbol) = Libdl.dlsym_e(lib, sym) != C_NULL
```
That 0.7 change is really annoying...

**Comment by ararslan** [comment]
I'm not sure whether the change to test/helpers.jl will work on other systems though.

**Comment by ararslan** [comment]
Actually `LIBC` isn't being used in that file, so I think we can just remove that.

**Comment by ararslan** [comment]
Looks like we're all good on Linux 0.7 now.

**Comment by rofinn** [comment]
Nice! I didn't realize we could skip specifying the libc library.

**Pull request merged**
